MethodDeclaration (MethodDeclaration) ::= <<
\<ul>
	\<ul>
		\<ul>Method Name:
			\<ul>\<b><MethodDeclaration.name>\</b>\</ul>
		\</ul>
		\<ul>Return Type:
			\<ul><MethodDeclaration.returnType2>\</ul>
		\</ul>		
		\<ul>Javadoc:
			\<ul>
				\<ul><MethodDeclaration.javadoc>\</ul> 			
 			\</ul>
		\</ul>		
		\<ul>Parameters:
			\<ul>
				\<ul><MethodDeclaration.parameters>\</ul>
				\<ul><length(MethodDeclaration.parameters)>\</ul>
 			\</ul>
		\</ul>
		\<ul>Position Start:
			\<ul>
				\<ul>\<a href="#<MethodDeclaration.startPosition>-<MethodDeclaration.length>"><MethodDeclaration.startPosition>\</a>\</ul> 			
 			\</ul>
		\</ul>
				
	\</ul>
\</ul>		
>>
